<script>
    var WebFontConfig = {
        google: {
            families: [
                'Roboto:100,300,400,400i,500,700',
                'Roboto+Condensed:300,400,700',
                'Mate:400i',
                'Yrsa:400',
            ]
        }
    };

    (function(d) {
        var wf = d.createElement('script'), s = d.scripts[0];
        wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js';
        wf.async = true;
        s.parentNode.insertBefore(wf, s);
    })(document);
</script>
<script src="../vendor/siroop/frontend/public/dist/js/default.min.js"></script>
<script src="../vendor/siroop/frontend/public/dist/js/vendor.min.js"></script>
</body>
</html>