<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width">
    <title>Responsive image live preview</title>
    <link rel="stylesheet" href="../vendor/siroop/frontend/public/dist/css/default.min.css">
    <link rel="stylesheet" href="../public/css/main.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,400i,500,700%7CRoboto+Condensed:300,400,700%7CMate:400i%7CYrsa:400" media="all">
</head>
<body>
<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" async=""></script>